# Generated by Django 5.2.4 on 2025-07-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='morada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
