# Generated by Django 5.2.4 on 2025-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_expiracao_anuncio',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
