# Generated by Django 5.2.4 on 2025-07-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0004_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tel',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
